services:

    ProtectedClient:
        class: Hitbtc\ProtectedClient
        arguments: ['%HitBTCApiKey%', '%HitBTCSecret%', '%HitBTCModeDemo%']
    InvestmentRepository:
        class: CriptoControl\Infrastructure\Persistence\Api\HitBTCInvestmentRepository
        arguments: ['@ProtectedClient']
    InMemoryInvestmentReadRepository:
        class: CriptoControl\Infrastructure\Persistence\InMemory\InMemoryInvestmentReadRepository
    GetInvestmentListHandler:
        class: CriptoControl\Application\Query\GetInvestmentListHandler
        arguments: ['@InvestmentRepository']
    GetInvestmentWithCurrencyHandler:
        class: CriptoControl\Application\Query\GetInvestmentWithCurrencyHandler
        arguments: ['@InvestmentRepository']
