services:

    ProtectedClient:
        class: Hitbtc\ProtectedClient
        arguments: ['%HitBTCApiKey%', '%HitBTCSecret%', '%HitBTCModeDemo%']
    InvestmentRepository:
        class: CriptoControl\Infrastructure\Persistence\Api\HitBTCInvestmentRepository
        arguments: ['@ProtectedClient']
    GetInvestmentListHandler:
        class: CriptoControl\Application\Query\GetInvestmentListHandler
        arguments: ['@InvestmentRepository']
    GetInvestmentWithCurrencyHandler:
        class: CriptoControl\Application\Query\GetInvestmentWithCurrencyHandler
        arguments: ['@InvestmentRepository']
    CoinMarketCapExchangeReadRepository:
        class: CriptoControl\Infrastructure\Persistence\Api\CoinMarketCapExchangeReadRepository
        arguments: ['%CoinMarketUrl%', '%CoinMarketApiKey%']
    GetExchangeForInvestmentHandler:
        class: CriptoControl\Application\Query\GetExchangeForInvestmentHandler
        arguments: ['@CoinMarketCapExchangeReadRepository']
    GetInvestmentByFiatHandler:
        class: CriptoControl\Application\Query\GetInvestmentByFiatHandler
        arguments: ['@GetInvestmentListHandler', '@GetExchangeForInvestmentHandler']