services:

    InMemoryInvestmentReadRepository:
            class: CriptoControl\Infrastructure\Persistence\InMemory\InMemoryInvestmentReadRepository
    GetInvestmentListHandler:
        class: CriptoControl\Application\Query\GetInvestmentListHandler
        arguments: ['@InMemoryInvestmentReadRepository']
