#!/usr/bin/env bash

docker run                                                                                                             \
    --rm                                                                                                               \
    --name criptocontrol_cli                                                                                           \
    -v ${PWD}:/data                                                                                   \
    -w /data                                                                                                           \
    criptocontrol_cli:latest                                                                                           \
    composer $@
